/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import core.AES;
import java.math.BigInteger;
import java.text.DecimalFormat;
import java.util.Base64;
import java.util.HexFormat;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author an
 */
public class GUIForm extends javax.swing.JFrame {

    /**
     * Creates new form GUIForm
     */
    public GUIForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgKhoa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb128 = new javax.swing.JRadioButton();
        rb192 = new javax.swing.JRadioButton();
        rb256 = new javax.swing.JRadioButton();
        tfKhoa = new javax.swing.JTextField();
        btnTaoKhoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfBanMaMaHoa = new javax.swing.JTextField();
        tfBanRoMaHoa = new javax.swing.JTextField();
        btnMaHoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelTGMaHoa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfBanRoGiaiMa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnGiaiMa = new javax.swing.JButton();
        labelTGGiaiMa = new javax.swing.JLabel();
        tfBanMaGiaiMa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnReset = new javax.swing.JButton();
        cbbChonCheDoGiaiMa = new javax.swing.JComboBox<>();
        cbbChonCheDoMaHoa = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Chương trình mã hóa và giải mã bằng mật mã AES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Bài tập nhóm 10");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Chọn độ dài khóa :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 20));

        bgKhoa.add(rb128);
        rb128.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rb128.setText("128");
        rb128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb128ActionPerformed(evt);
            }
        });
        jPanel1.add(rb128, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        bgKhoa.add(rb192);
        rb192.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rb192.setText("192");
        jPanel1.add(rb192, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        bgKhoa.add(rb256);
        rb256.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rb256.setText("256");
        rb256.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb256ActionPerformed(evt);
            }
        });
        jPanel1.add(rb256, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        tfKhoa.setEditable(false);
        tfKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tfKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 680, 40));

        btnTaoKhoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnTaoKhoa.setText("Tạo");
        btnTaoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaoKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 120, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Mã Hóa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Bản rõ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Bản mã");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 40));

        tfBanMaMaHoa.setEditable(false);
        tfBanMaMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBanMaMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBanMaMaHoaActionPerformed(evt);
            }
        });
        jPanel1.add(tfBanMaMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 680, 40));

        tfBanRoMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tfBanRoMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 680, 40));

        btnMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMaHoa.setText("Mã hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Thời gian mã hóa: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        labelTGMaHoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTGMaHoa.setText("0 ms");
        jPanel1.add(labelTGMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Giải mã");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Bản mã");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 60, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Bản rõ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 50, 40));

        tfBanRoGiaiMa.setEditable(false);
        tfBanRoGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tfBanRoGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 680, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Thời gian giải mã: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, -1, -1));

        btnGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 130, -1));

        labelTGGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTGGiaiMa.setText("0 ms");
        jPanel1.add(labelTGGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, -1, -1));

        tfBanMaGiaiMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBanMaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBanMaGiaiMaActionPerformed(evt);
            }
        });
        jPanel1.add(tfBanMaGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 680, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 910, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 910, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 910, 20));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        cbbChonCheDoGiaiMa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base64", "HEX" }));
        cbbChonCheDoGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonCheDoGiaiMaActionPerformed(evt);
            }
        });
        jPanel1.add(cbbChonCheDoGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 100, 30));

        cbbChonCheDoMaHoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base64", "HEX" }));
        cbbChonCheDoMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonCheDoMaHoaActionPerformed(evt);
            }
        });
        jPanel1.add(cbbChonCheDoMaHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Chế độ: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Chế độ: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static AES cipher;
    private static DecimalFormat decimalFormat = new DecimalFormat("#.###########");
    private static String keyString;

    private static final String BASE64 = "Base64";
    private static final String HEX = "HEX";

    private static String generateRandomString(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(characters.length());
            sb.append(characters.charAt(index));
        }
        return sb.toString();
    }

    public static String bytesToHex(byte[] bytes) {
        BigInteger bigInt = new BigInteger(1, bytes);
        String hexString = bigInt.toString(16);
        // Đảm bảo chuỗi hex có đúng độ dài bằng đúng bằng số byte trong mảng
        int paddingLength = (bytes.length * 2) - hexString.length();
        if (paddingLength > 0) {
            return String.format("%0" + paddingLength + "d", 0) + hexString;
        } else {
            return hexString;
        }
    }

    public static byte[] hexStringToByteArray(String hexString) {
        int len = hexString.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hexString.charAt(i), 16) << 4)
                    + Character.digit(hexString.charAt(i + 1), 16));
        }
        return data;
    }

    private void rb128ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rb128ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rb128ActionPerformed

    private void rb256ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rb256ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rb256ActionPerformed

    private void tfBanMaMaHoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfBanMaMaHoaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfBanMaMaHoaActionPerformed

    private void tfBanMaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfBanMaGiaiMaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfBanMaGiaiMaActionPerformed

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMaHoaActionPerformed
        // TODO add your handling code here:
        if (tfKhoa == null || tfKhoa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng tạo khóa !");
            return;
        }
        if (tfBanRoMaHoa == null || tfBanRoMaHoa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi mã hóa !");
            return;
        } else {
            try {
                cipher = new AES(keyString.getBytes());
                long startTimeEncrypt = System.nanoTime();
                byte[] encryptResult = cipher.ECB_encrypt(tfBanRoMaHoa.getText().getBytes());
                long endTimeEncrypt = System.nanoTime();
                String selectedItem = cbbChonCheDoMaHoa.getSelectedItem().toString();
                System.out.println("mode now : " + cbbChonCheDoMaHoa.getSelectedItem().toString());
                String encryptResultStr;
                if (selectedItem.equals(BASE64)) {
                    encryptResultStr = Base64.getEncoder().encodeToString(encryptResult);
                } else {
                    encryptResultStr = bytesToHex(encryptResult);
                }
                double encryptTime = (endTimeEncrypt - startTimeEncrypt) / 1e6;
                JOptionPane.showMessageDialog(this, "Mã hóa thành công");
                tfBanMaMaHoa.setText(encryptResultStr);
                labelTGMaHoa.setText(String.valueOf(encryptTime) + " ms");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Mã hóa thất bại!!!");

            }
        }
    }// GEN-LAST:event_btnMaHoaActionPerformed

    private void btnTaoKhoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTaoKhoaActionPerformed
        // TODO add your handling code here:
        if (rb128.isSelected()) {
            JOptionPane.showMessageDialog(this, "Tạo khóa 128 thành công !");
            String key = generateRandomString(16);
            keyString = key;
            tfKhoa.setText(key);
        } else if (rb192.isSelected()) {
            JOptionPane.showMessageDialog(this, "Tạo khóa 192 thành công");
            String key = generateRandomString(24);
            keyString = key;
            tfKhoa.setText(key);

        } else if (rb256.isSelected()) {
            JOptionPane.showMessageDialog(this, "Tạo khóa 256 thành công");
            String key = generateRandomString(32);
            keyString = key;
            tfKhoa.setText(key);

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn kiểu khóa !");
            return;
        }
    }// GEN-LAST:event_btnTaoKhoaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGiaiMaActionPerformed
        // TODO add your handling code here:
        if (tfKhoa == null || tfKhoa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập/tạo khóa !");
            return;
        }

        if (tfBanMaGiaiMa == null || tfBanMaGiaiMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi giải mã !");
            return;
        } else {
            try {
                cipher = new AES(keyString.getBytes());
                String selectedItem = cbbChonCheDoGiaiMa.getSelectedItem().toString();
                System.out.println("Option : " + selectedItem);
                byte[] input;
                if (selectedItem.equals(BASE64)) {
                    input = Base64.getDecoder().decode(tfBanMaGiaiMa.getText());
                } else {
                    input  = hexStringToByteArray(tfBanMaGiaiMa.getText());
                }
                long startTimeDecrypt = System.nanoTime();
                byte[] decryptResult = cipher.ECB_decrypt(input);
                long endTimeDecrypt = System.nanoTime();
                double decryptTime = (endTimeDecrypt - startTimeDecrypt) / 1e6;
                JOptionPane.showMessageDialog(this, "Giải mã thành công");
                tfBanRoGiaiMa.setText(new String(decryptResult).trim());
                labelTGGiaiMa.setText(String.valueOf(decryptTime) + " ms");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giải mã thất bại !!!!!!!!!");
            }
        }

    }// GEN-LAST:event_btnGiaiMaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        bgKhoa.clearSelection();
        tfBanMaGiaiMa.setText("");
        tfBanMaMaHoa.setText("");
        tfBanRoMaHoa.setText("");
        tfBanRoGiaiMa.setText("");
        tfKhoa.setText("");
        labelTGGiaiMa.setText("0 ms");
        labelTGMaHoa.setText("0 ms");
    }// GEN-LAST:event_btnResetActionPerformed

    private void cbbChonCheDoMaHoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbChonCheDoMaHoaActionPerformed
        // TODO add your handling code here:
        String txtCbbMaHoa = cbbChonCheDoMaHoa.getSelectedItem().toString();
        System.out.println("selected: " + txtCbbMaHoa);
    }// GEN-LAST:event_cbbChonCheDoMaHoaActionPerformed

    private void cbbChonCheDoGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbChonCheDoGiaiMaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbbChonCheDoGiaiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgKhoa;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTaoKhoa;
    private javax.swing.JComboBox<String> cbbChonCheDoGiaiMa;
    private javax.swing.JComboBox<String> cbbChonCheDoMaHoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelTGGiaiMa;
    private javax.swing.JLabel labelTGMaHoa;
    private javax.swing.JRadioButton rb128;
    private javax.swing.JRadioButton rb192;
    private javax.swing.JRadioButton rb256;
    private javax.swing.JTextField tfBanMaGiaiMa;
    private javax.swing.JTextField tfBanMaMaHoa;
    private javax.swing.JTextField tfBanRoGiaiMa;
    private javax.swing.JTextField tfBanRoMaHoa;
    private javax.swing.JTextField tfKhoa;
    // End of variables declaration//GEN-END:variables
}
